### ISSUE TITLE
math.distribution not available

### ISSUE THREAD

**Issue by purplecones** [ecwyne/meteor-mathjs#4]
Trying to use math.distribution but that method is not available. 

Available in mathjs repo at: 

https://github.com/josdejong/mathjs/blob/1f000925b778c06ef8a0fd788deee840bcf78ea5/lib/function/probability/distribution.js

**Comment by ecwyne** [comment]
Should be fixed with https://github.com/ecwyne/meteor-mathjs/commit/92f6f86e87aab65fa884c672d0db8b92a4dcc354
