### ISSUE TITLE
Upgrade to the latest version of math.js

### ISSUE THREAD

**Issue by bastiW** [ecwyne/meteor-mathjs#6]
Hi there,

could you please upgrade your package to the latest version of math.js. 

Inside the new version there are some problems fixed. For example:

```
var b = math.fraction(0.3);   
var c = math.number(b);  
VM3655:131 Uncaught TypeError: Unexpected type of argument in function number (expected: number or BigNumber or Unit or string or Array or Matrix, actual: Fraction, index: 0)(…)
```

In the new math.js version 2.7.0 you get the expected result:

```
var b = math.fraction(0.3);   
var c = math.number(b);
undefined
c
0.3

```

This example code can also be found inside the documentation http://mathjs.org/docs/datatypes/fractions.html#conversion

Best regards
Basti

**Comment by ecwyne** [comment]
Updated, though packages such as these will be rendered unnecessary with the coming of Meteor 1.3

https://atmospherejs.com/meteor/modules
